#define MSG_BUFFER_SIZE	(20)

#define IMPULSECOUNTER_MQTT_SUBSCRIPTION_RETAIN_TIMEOUT (500)

#define IMPULSECOUNTER_VALUE_TOPIC "/value"
#define IMPULSECOUNTER_VALUE_DETAILED_TOPIC "/value_detailed"
#define IMPULSECOUNTER_PULSE_TOPIC "/pulse"
