#define THERMO_SUBTOPIC_DEV "/devices"
#define THERMO_SUBTOPIC_BUS "/busses"
#define THERMO_SUBTOPIC_RESCAN "/rescan"

#define THERMO_SENSOR_TIMEOUT (5000)
#define THERMO_RESOLUTION (11)

#define THERMO_MAX_LEN_BASE_TOPIC (30)

#define THERMO_DEV_ADD "/0000000000000000/value"
#define THERMO_LENGTH_DEVICE (THERMO_MAX_LEN_BASE_TOPIC + (sizeof(THERMO_SUBTOPIC_DEV) - 1) + (sizeof(THERMO_DEV_ADD) - 1) + 1)

#define THERMO_BUS_ADD "/#"
#define THERMO_LENGTH_BUS (THERMO_MAX_LEN_BASE_TOPIC + (sizeof(THERMO_SUBTOPIC_BUS) - 1) + (sizeof(THERMO_BUS_ADD) - 1) + 1)